name: message_board_app
description: A Message Board App for CSC 4360 - Mobile App Development

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0

  # Add other dependencies if needed
  # Example: flutter_chat: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # No assets are needed since we're using icons
  # If you decide to add assets in the future, uncomment and add paths here
  # assets:
  #   - assets/icons/
