// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpN-hDECJLo08F42RMaS-3ZD3LFDd_gQk',
    appId: '1:1083438825145:web:66324898b154cd36eb6568',
    messagingSenderId: '1083438825145',
    projectId: 'txterap',
    authDomain: 'txterap.firebaseapp.com',
    storageBucket: 'txterap.firebasestorage.app',
    measurementId: 'G-Q6Z1RLSHHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD04lCZNfdgtGhrXTxiqXz9CQ5ESAsmXPw',
    appId: '1:1083438825145:android:075528e82d673226eb6568',
    messagingSenderId: '1083438825145',
    projectId: 'txterap',
    storageBucket: 'txterap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNnLrqXrUdRxeJ0CpTc3kmrAqsJM5Lsw',
    appId: '1:1083438825145:ios:48a2e58a53744d56eb6568',
    messagingSenderId: '1083438825145',
    projectId: 'txterap',
    storageBucket: 'txterap.firebasestorage.app',
    iosBundleId: 'com.example.nice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiNnLrqXrUdRxeJ0CpTc3kmrAqsJM5Lsw',
    appId: '1:1083438825145:ios:48a2e58a53744d56eb6568',
    messagingSenderId: '1083438825145',
    projectId: 'txterap',
    storageBucket: 'txterap.firebasestorage.app',
    iosBundleId: 'com.example.nice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpN-hDECJLo08F42RMaS-3ZD3LFDd_gQk',
    appId: '1:1083438825145:web:c1132bacbcf88ac2eb6568',
    messagingSenderId: '1083438825145',
    projectId: 'txterap',
    authDomain: 'txterap.firebaseapp.com',
    storageBucket: 'txterap.firebasestorage.app',
    measurementId: 'G-QGT88TXYG6',
  );
}
